### ISSUE TITLE
Prepare for Release

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-azuredevops#1]
Tracking items for release:

* [x] Depend on the most recent release of the upstream Terraform provider and have mapped all data sources and resources which make sense.
* [x] Have the various configuration options for the provider listed in the README file such that package consumers can easily find them.
* [ ] Have documentation ready to publish (in the pulumi/docs repo)
* [x] Have at least one example running in CI against the provider
* [x] Tag a version and ensure it's published as latest

**Comment by stack72** [comment]
@tmeckel I just pushed some initial examples - for us, examples are like acceptance tests :) So if you want to add more then that's cool - just send a PR and the automation will run them before we merge them

I just tagged v1.0.0 of this provider - this is what we will use as our base release going forward!

**Comment by tmeckel** [comment]
@stack72 Fine, I'll copy over the examples from my repo in a PR.

About the version: shouldn't it not be aligned with the version of the Terraform provider? Currently the Terraform provider is at v0.0.1.

**Comment by stack72** [comment]
it is :) I updated it! check out provider/go.mod

**Comment by tmeckel** [comment]
@stack72 😁 No I meant the release (version) tag of the Pulumi provider

**Comment by stack72** [comment]
oh I see! no, we version our providers differently - we will respect major version bumps of course and will act accordingly

**Comment by stack72** [comment]
Docs PR is now open https://github.com/pulumi/docs/pull/3625
