### ISSUE TITLE
All resources in the Pulumi API documents show as Depreciated 

### ISSUE THREAD

**Issue by tap1992** [pulumi/pulumi-azuredevops#149]
### What happened?

Looking into using this provider but all the resources show as depreciated which makes me hesitant to onboard it.

Screenshot:
![image](https://user-images.githubusercontent.com/75792610/231689865-6d30c90c-3dd8-4468-b2b3-6365581071d0.png)

### Expected Behavior

The resource are up to date and available (not showing as depreciated) 

### Steps to reproduce

Go to any of the resources within: https://www.pulumi.com/registry/packages/azuredevops/api-docs/

E.g.: https://www.pulumi.com/registry/packages/azuredevops/api-docs/agent/pool/

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jazzyfresh** [comment]
Thank you for reporting this! It seems like a change in the Azure API could have these resources moved to the top level. For the example you listed, BuildDefinition was moved to the top level package, https://www.pulumi.com/registry/packages/azuredevops/api-docs/builddefinition/ Does this resource work for you? This will help us identify if it's a docsgen issue or a bug in the generated schema.

**Comment by tap1992** [comment]
Ahh thanks for that! I hadn't noticed the resources at the top level!
