### ISSUE TITLE
Optional parameters being treated as mandatory?

### ISSUE THREAD

**Issue by mflanneryii** [pulumi/pulumi-azuredevops#33]
It looks like there may be either a documentation problem in [python examples for Git resources](https://www.pulumi.com/docs/reference/pkg/azuredevops/git/) or a potential issue with the tfgen bindings for Python.

Specifically it appears that optional parameters are being flagged as mandatory somewhere in the Pulumi stack.

Using the 'create git repository' example from the docs bombs out with ```resource 'repo' has a problem: "initialization.0.source_url": all of `initialization.0.source_type,initialization.0.source_url` must be specified"```

As per the docs those parameters are optional outside of `init_type='Import'`. 

I've tested against 1.0.0, 1.1.1 and 1.2.0 versions of pulumi-azuredevops and they all behave the same way. 

I've tested directly using the [terraform provider](https://github.com/microsoft/terraform-provider-azuredevops) and it does not seem to have this issue.

**Workaround:** It's easy enough to workaround by just passing dummy values the parameters _(though they still have to meet input validation requirements)_ so it's more of an awkward annoyance than anything else.

**Comment by stack72** [comment]
Hi @mflanneryii 

My apologies you are hitting this - please can you give me a sample of code that I can use to diagnose and triage this?

Thanks

Paul

**Comment by mflanneryii** [comment]
No worries, like I mentioned I found a workaround easily enough, but for replication I was using this example from the docs:

```python
import pulumi
import pulumi_azuredevops as azuredevops

project = azuredevops.Project("project",
    visibility="private",
    version_control="Git",
    work_item_template="Agile"
)

repo = azuredevops.Git("repo",
    project_id=project.id,
    initialization=azuredevops.GitInitializationArgs(
        init_type="Clean",
    )
)
```

**Comment by stack72** [comment]
Hi @mflanneryii 

So after investigating this, I was able to find that the current provider is against v1.1.1 of the TF provider which actually had a default "" in there:

```
			"initialization": {
				Type:     schema.TypeList,
				Required: true,
				MaxItems: 1,
				MinItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"init_type": {
							Type:     schema.TypeString,
							Required: true,
							ValidateFunc: validation.StringInSlice([]string{
								string(RepoInitTypeValues.Clean),
								string(RepoInitTypeValues.Fork),
								string(RepoInitTypeValues.Import),
								string(RepoInitTypeValues.Uninitialized),
							}, false),
						},
						"source_type": {
							Type:         schema.TypeString,
							Optional:     true,
							ForceNew:     true,
							ValidateFunc: validation.StringInSlice([]string{"Git"}, false),
							RequiredWith: []string{"initialization.0.source_url"},
						},
						"source_url": {
							Type:         schema.TypeString,
							Optional:     true,
							ForceNew:     true,
							Default:      "",
							RequiredWith: []string{"initialization.0.source_type"},
							ValidateFunc: validation.IsURLWithHTTPorHTTPS,
						},
					},
				},
			},
```

If you can see the RequiredWith, you will see why there is the bug there. I am going to be working on pushing #34 across the line today which will fix this up

Paul
