### ISSUE TITLE
(dotnet) AzureDevOps.Inputs.BranchPolicyMinReviewersSettingsArgs always has conflicts

### ISSUE THREAD

**Issue by marklam** [pulumi/pulumi-azuredevops#38]
`BranchPolicyMinReviewersSettingsArgs` has properties `OnPushResetAllVotes` and  `OnPushResetApprovedVotes` specified as `Input<bool>`, but I think they should be `Input<bool?>`

Attempting to use the `BranchPolicyMinReviewers` will always fail because both properties are defaulted to bool, but it is an [error to specify both values](https://github.com/microsoft/terraform-provider-azuredevops/commit/1f0948169de5bd29e81884222814ca9f92399094).

## Expected behavior
Either `OnPushResetAllVotes` or `OnPushResetApprovedVotes` can be true

## Current behavior
Any use of `BranchPolicyMinReviewers` produces an error of the form
```
    error: azuredevops:index/branchPolicyMinReviewers:BranchPolicyMinReviewers resource 'TestProjectReview' has a problem: "settings.0.on_push_reset_all_votes": conflicts with settings.0.on_push_reset_approved_votes
    error: azuredevops:index/branchPolicyMinReviewers:BranchPolicyMinReviewers resource 'TestProjectReview' has a problem: "settings.0.on_push_reset_approved_votes": conflicts with settings.0.on_push_reset_all_votes
```

## Steps to reproduce
```fsharp
let createReviewPolicy projectId (repo : Git) repoName =
    let reviewScope =
        AzureDevOps.Inputs.BranchPolicyMinReviewersSettingsScopeArgs(
            RepositoryId = io repo.Id
        )

    let reviewPolicySettings =
        AzureDevOps.Inputs.BranchPolicyMinReviewersSettingsArgs(
            ReviewerCount            = input 2,
            OnPushResetAllVotes      = input true,
            Scopes                   = inputList [ input reviewScope ]
        )

    let reviewPolicyArgs =
        AzureDevOps.BranchPolicyMinReviewersArgs(
            ProjectId = projectId,
            Settings  = input reviewPolicySettings
        )

    let reviewPolicy =
        AzureDevOps.BranchPolicyMinReviewers(
            repoName + "Review",
            reviewPolicyArgs
        )
    ()
```

## Context (Environment)
Trying to create an Azure DevOps PR approval policy from Pulumi

## Affected feature
Pulumi.AzureDevOps dotnet SDK

**Comment by Jono20201** [comment]
@marklam Did you ever manage to work around this?

**Comment by marklam** [comment]
No, sorry - that bit of the code remained* commented-out pending a fix for this issue 

*past tense because the project I used it in is no longer under development.

**Comment by Jono20201** [comment]
Is it possible to tag this with kind/bug?

Wish I had enough knowledge of Go/terraform bridge to fix this myself!

**Comment by samuelbertrand** [comment]
I have the same issue when using Python. I tried to use the code sample from the [official documentation](https://www.pulumi.com/registry/packages/azuredevops/api-docs/branchpolicyminreviewers/#example-usage), and I have the same behavior:
```python
example_branch_policy_min_reviewers = azuredevops.BranchPolicyMinReviewers("exampleBranchPolicyMinReviewers",
    project_id=example_project.id,
    enabled=True,
    blocking=True,
    settings=azuredevops.BranchPolicyMinReviewersSettingsArgs(
        reviewer_count=7,
        submitter_can_vote=False,
        last_pusher_cannot_approve=True,
        allow_completion_with_rejects_or_waits=False,
        on_push_reset_approved_votes=True,
        on_last_iteration_require_vote=False,
        scopes=[
            azuredevops.BranchPolicyMinReviewersSettingsScopeArgs(
                repository_id=example_git.id,
                repository_ref=example_git.default_branch,
                match_type="Exact",
            ),
            azuredevops.BranchPolicyMinReviewersSettingsScopeArgs(
                repository_id=None,
                repository_ref="refs/heads/releases",
                match_type="Prefix",
            ),
            azuredevops.BranchPolicyMinReviewersSettingsScopeArgs(
                match_type="DefaultBranch",
            ),
        ],
    ))
```

Output:
```
error: azuredevops:index/branchPolicyMinReviewers:BranchPolicyMinReviewers resource 'exampleBranchPolicyMinReviewers' has a problem: Conflicting configuration arguments: "settings.0.on_push_reset_approved_votes": conflicts with settings.0.on_push_reset_all_votes. Examine values at 'BranchPolicyMinReviewers.Settings.OnPushResetApprovedVotes'.
error: azuredevops:index/branchPolicyMinReviewers:BranchPolicyMinReviewers resource 'exampleBranchPolicyMinReviewers' has a problem: Conflicting configuration arguments: "settings.0.on_push_reset_all_votes": conflicts with settings.0.on_push_reset_approved_votes. Examine values at 'BranchPolicyMinReviewers.Settings.OnPushResetAllVotes'.
```

I didn't find any workaround.

**Comment by Jono20201** [comment]
Related: 

https://github.com/pulumi/pulumi/issues/6175
https://github.com/pulumi/pulumi/issues/12105

I asked for advice in Slack for fixing, and the response from a Pulumi Eng was:

> Honestly I wouldn't try, this is a bug in codegen (for all language really but we've only got issues for [TypeScript](https://github.com/pulumi/pulumi/issues/6175) and [Python](https://github.com/pulumi/pulumi/issues/12105))
I happened to look into this last week thinking it might be simple. It is horrifically complicated, breaks just about everything in all the code generators.

**Comment by Jono20201** [comment]
For anyone who really wants something like this, I created a component to configure min reviewers using the 'Command' package.

https://www.pulumi.com/registry/packages/command/

Here is some code: https://gist.github.com/Jono20201/5ad933a31fa677d14a557f9642697375

**Comment by lukehoban** [comment]
I believe there are two paths to addressing this:

1. Implement a complete fix for https://github.com/pulumi/pulumi-terraform-bridge/issues/1095, which we likely need to be very careful with as this may have subtle interactions with other providers.
2. Fork the upstream to remove the `default` values for two of the affected properties - which is presumably what is causing trouble here (the combination of `default` and `conflicts_with`).

**Comment by VenelinMartinov** [comment]
We just released https://github.com/pulumi/pulumi-azuredevops/releases/tag/v2.14.1 which has a fix for this.
