### ISSUE TITLE
Ability to Create a ReleaseDefinition

### ISSUE THREAD

**Issue by andrewdmoreno** [pulumi/pulumi-azuredevops#45]
For Azure Dev Ops customers still using the classic release pipelines feature, it would be helpful to be able to create a Release Definition resource.

This resource is documented in ADO rest api: [https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions/create?view=azure-devops-rest-6.0](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions/create?view=azure-devops-rest-6.0)

This would address the request for samples in issue #17 .

**Comment by tmeckel** [comment]
@andrewdmoreno I think such enhancements should be addressed in the upstream repository https://github.com/microsoft/terraform-provider-azuredevops

Please give a `thumbs up` on the existing issue about creating a ReleaseDefinition resource -> https://github.com/microsoft/terraform-provider-azuredevops/issues/49 and you can ask  @exocom about the status of his PR about release pipelines: https://github.com/microsoft/terraform-provider-azuredevops/pull/178
