### ISSUE TITLE
VariableGroup doesn't work with key_vault parameter

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-azuredevops#52]
Hi, I've tried to create a variable group connected to azure keyvault:

```python
azuredevops.VariableGroup(
        "devops-secret-storage-account-name-vg",
        project_id=project.id,
        allow_access=False,
        key_vault=azuredevops.VariableGroupKeyVaultArgs(
            name=vault.name,
            service_endpoint_id=service_endpoint_rm.id,
        ),
        variables=[
            azuredevops.VariableGroupVariableArgs(
                name=secret_storage_key.name,
            ),
        ]
    )
```

If `key_vault` parameter is filled these errors are raised:
```
error: azuredevops:index/variableGroup:VariableGroup resource 'devops-secret-storage-account-name-vg' has a problem: "variable.0.value": conflicts with key_vault
error: azuredevops:index/variableGroup:VariableGroup resource 'devops-secret-storage-account-name-vg' has a problem: "variable.0.secret_value": conflicts with key_vault
error: azuredevops:index/variableGroup:VariableGroup resource 'devops-secret-storage-account-name-vg' has a problem: "variable.0.is_secret": conflicts with key_vault
```
`variables` parameter has to be set because of mapping of variable group to secrets names. (see https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)

**Comment by lblackstone** [comment]
@stack72 Do you know if this is an upstream bug?

**Comment by tmeckel** [comment]
@lblackstone @stack72 according to the code from the upstream repo, the error message is correct:

https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/internal/service/taskagent/resource_variable_group.go

![image](https://user-images.githubusercontent.com/14177833/119230342-0e665d00-bb1c-11eb-87ff-7591d58f63cd.png)

But as far as I know using this code inside Terraform never created such an error message, when a `azuredevops_variable_group` is created and connect to an Azure KeyVault. Perhaps such a schema configuration isn't supported by `TFBridge`.

**Comment by sheldonhull** [comment]
Ran into this as well, and haven't found any good answer on how to get past this. Variable group is causing failure. If I try to pass nil `* invalid value for required argument 'Variables'` and any other combinations of input doesn't seem to work.

**Comment by sheldonhull** [comment]
Possibly another related duplicate: https://github.com/pulumi/pulumi-azuredevops/issues/62

**Comment by sheldonhull** [comment]
Updated to latest `v2.4.0` and it doesn't seem to have resolved this issue. Still have to separate this out.
