### ISSUE TITLE
Git repository import doesn't work

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-azuredevops#56]
It is not possible to import existing git repository:
`pulumi import azuredevops:index/git:Git repository <project_id>/<repo_name>`
ends with:
`error: azuredevops:index/git:Git resource 'repository' has a problem: Missing required property 'initialization'`

Thanks!

**Comment by lukehoban** [comment]
I've added this to https://github.com/pulumi/pulumi/issues/7160 which is tracking the general class of issues related to this.  We'll explore options for addressing this there.  For now, you will likely need to hand-edit the imported resource specification to ensure that it is valid for this resource.
