### ISSUE TITLE
Azure DevOps Kubernetes Service Endpoint kubeconfigs are not updated

### ISSUE THREAD

**Issue by kralikba** [pulumi/pulumi-azuredevops#59]
When creating a Kubernetes Service Endpoint based in a Kubeconfig using the Pulumi Azure DevOps plugin,
creation succeeds and created endpoint works.

When, later on, this kubeconfig gets modified (e.g. because of access token rotation), Pulumi reports successful updates, yet the service endpoint does not get updated.

**Comment by lukehoban** [comment]
> When, later on, this kubeconfig gets modified (e.g. because of access token rotation), Pulumi reports successful updates, yet the service endpoint does not get updated.

Can you share the diff you see during the update of the `kubeconfig`?

This sounds a lot like https://github.com/microsoft/terraform-provider-azuredevops/issues/76 in the upstream provider, but that was apparently fixed some time ago?  Are you using a recent version - and if so, can you share details of the version number and the repro steps?

**Comment by stack72** [comment]
Hi @kralikba 

We've not heard back from you on this so we are going to close this out - if you are still having an issue here, please do let us know

Paul
