### ISSUE TITLE
Importing a VariableGroup fails when it has variables

### ISSUE THREAD

**Issue by tomachristian** [pulumi/pulumi-azuredevops#67]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am trying to import an existing VariableGroup using `pulumi import`. It fails with:

```
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.0.content_type": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.0.enabled": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.0.expires": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.1.content_type": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.1.enabled": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.1.expires": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.2.content_type": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.2.enabled": this field cannot be set
    error: azuredevops:index/variableGroup:VariableGroup resource 'some-variable-group' has a problem: "variable.2.expires": this field cannot be set
```

### Steps to reproduce

1. Have an Azure DevOps variable group that already has some variables defined
2. Try to import this variable group using `pulumi import`

Expected: The VariableGroup and its defined variables are imported successfully. Pulumi does not complain avout `ContentType`, `Expires` or `Enabled`
Actual: Pulumi complains that it cannot set either of `ContentType`, `Expires` or `Enabled` when in fact these properties shouldn't even be set during import.

**Comment by leezen** [comment]
As a workaround, are you able to import programmatically via the `import` resource option?

**Comment by leezen** [comment]
Sorry, I must've missed the notification for your original reply.

If I'm understanding your flow correctly, I think the following could work?
1. `pulumi stack export` from the local self-managed backed
2. `pulumi stack import` into the newly provisioned Blob Container-based backend
3. `pulumi stack change-secrets-provider` after the import to swap from passphrase to using the Key Vault.
4. `pulumi up` for any additional changes you want to make.

This way, you've imported the state file itself and you're not relying on trying to import the resources via reads. At that point, you should be able to operate against the imported stack.

**Comment by tomachristian** [comment]
That’s an excelent idea, clearly simplifies my workflow and eliminates the need for manual imports. Will definitely try it. Thank you very much!
