### ISSUE TITLE
Cannot create projects using scoped PAT

### ISSUE THREAD

**Issue by tksrc** [pulumi/pulumi-azuredevops#68]
## Hello!

I am seeing `401 Unauthorized` messages when attempting to create Azure DevOps projects using a PAT that has been scoped. The interesting thing is, even if I select ALL scopes under the Custom Scope settings of the token, I am still seeing the same 401 error.

If, however, I revert to Full Scope access for my token, everything works. 

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

1. Create an Azure DevOps [Personal Access Token](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?bc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Fbreadcrumb%2Ftoc.json&toc=%2Fazure%2Fdevops%2Fmarketplace-extensibility%2Ftoc.json&view=azure-devops&tabs=preview-page)
2. Under `Scopes` choose `Custom defined`
3. For the sake of testing, select ALL scopes. 
4. Use the [project resource](https://www.pulumi.com/registry/packages/azuredevops/api-docs/project/) to create a new project

Expected: 

New Azure DevOps project to be created.

Actual: 

```
error: Request returned status: 401 Unauthorized
error: update failed
```

snippet from the verbose logging generated:

```
I1028 11:23:59.820606   25989 provider_plugin.go:1523] provider received rpc error `Unknown`: `Request returned status: 401 Unauthorized`
I1028 11:23:59.820674   25989 provider_plugin.go:1526] rpc error kind `Unknown` may not be recoverable
I1028 11:23:59.820691   25989 provider_plugin.go:758] Provider[azuredevops, 0xc001608540].Create(urn:pulumi:shared::kirk-iadp-core-shared::azuredevops:index/project:Project::adp-shr-uks-adoproj-data-platform) failed: Request returned status: 401 Unauthorized
I1028 11:23:59.820748   25989 eventsink.go:86] eventSink::Error(<{%reset%}>Request returned status: 401 Unauthorized<{%reset%}>)
I1028 11:23:59.820841   25989 snapshot.go:316] SnapshotManager: createSnapshotMutation.End(..., false)
I1028 11:23:59.820857   25989 snapshot.go:536] SnapshotManager.markOperationComplete(urn:pulumi:shared::kirk-iadp-core-shared::azuredevops:index/project:Project::adp-shr-uks-adoproj-data-platform)
[38;5;1merror: [0m[0mRequest returned status: 401 Unauthorized[0m
I1028 11:24:00.163809   25989 step_executor.go:327] StepExecutor worker(2): step create on urn:pulumi:shared::kirk-iadp-core-shared::azuredevops:index/project:Project::adp-shr-uks-adoproj-data-platform failed with an error: Request returned status: 401 Unauthorized
I1028 11:24:00.163863   25989 step_executor.go:327] StepExecutor worker(2): step create on urn:pulumi:shared::kirk-iadp-core-shared::azuredevops:index/project:Project::adp-shr-uks-adoproj-data-platform failed, signalling cancellation
```

Provider versions affected: 2.1.1 2.20

**Comment by jkodroff** [comment]
Per the TF upstream docs:

> The account corresponding to the token will need "owner" privileges for this organization

I take this to mean that a scoped token will not work with this provider. Submitting a PR to update our docs.
